In [63]:
from scipy.integrate import quad, dblquad
from numpy import exp, log as ln, e, isclose
from scipy import optimize

# make sure to do a pip install scipy

In [64]:
def integrateFunction(x):
    return x

In [65]:
def integrateFn(x, a, b):
    return x*a+b

In [66]:
a = 3
b = 2


In [67]:
# when using the quad library, you do not pass in arguments to the 
# function like normal. Quad comes with an args argument
# where you should pass in the arguments that should go into the function
quad(integrateFn, 0, 1, args=(a, b))

(3.5, 3.885780586188048e-14)

In [68]:
def moreComplex(x):
    return x**2 + 2*x + 3

In [69]:
quad(moreComplex, 0, 1)

(4.333333333333333, 4.810966440042345e-14)

In [70]:
def integrateExp(x):
    return exp(x)

In [71]:
# this should tell you that the values gotten from
# these integration techniques are not exact, but are
# very very good approximations

# use the numpy.isclose function to see if stuff is close enough
# to deem it a reasonable enough approximation with little error
y = quad(integrateExp, ln(1), ln(2))
print(isclose(y[0], 1))

True


In [72]:
# let us perform some double integrals

# y must be the first argument, and x the second
f = lambda y, x: x + y**2
dblquad(f, 0, 2, lambda x: x, lambda x: x**2)

(6.095238095238096, 2.4838925067764726e-13)

In [73]:
# optimization
print("Welcome back!")

Welcome back!


In [75]:
toMinimize = lambda x: x**2+ 3*x 

a = optimize.minimize(toMinimize, 0, method='bfgs')
b = optimize.root(toMinimize, [-100, 100], method="hybr")


In [81]:
from scipy import linalg
import numpy as np

matrix = np.array([
    [10, 4],
    [9, 7]
])

matrix

array([[10,  4],
       [ 9,  7]])

In [77]:
type(matrix)

numpy.ndarray

In [80]:
# common linear algebra techniques

print("Inverse: ", linalg.inv(matrix))
print("Determinant: ", linalg.det(matrix))

tt = np.array([1, 2])
linalg.solve(matrix, tt)

Inverse:  [[ 0.20588235 -0.11764706]
 [-0.26470588  0.29411765]]
Determinant:  34.0


array([-0.02941176,  0.32352941])

In [82]:
# how to calculate eigenvalues and eigenvectors
test_rating_data = np.array([
    [5, 8],
    [7, 9]
])

# print the EigenValues
eigenvalues, eigenvector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenvalues
print(first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [86]:
# print first eigenvectors
print(eigenvector[:, 0])

# print second eigenvector
print(eigenvector[:, 1])

[-0.81220939  0.58336601]
[-0.63447346 -0.77294465]


In [87]:
from scipy.stats import norm

# location is the mean and scale is the standard deviation for normal distribution

In [98]:
# read up about random variables
# look up the scipy docs and see what these arguments do to the result
norm.rvs(loc=0, scale=1, size=10)

array([-0.80674852,  0.09086689,  1.03487199, -0.16224431,  2.36591293,
       -0.41603447,  1.20710798,  1.58092575, -1.86512879, -1.05090736])

In [99]:
# need to understand what that 5 there does
norm.cdf(5, loc=1, scale=2)

0.9772498680518208

In [100]:
# will definitely look more into this package and how to use it
norm.pdf(9, loc=0, scale=1)

1.0279773571668917e-18