In [1]:
from scipy.integrate import quad, dblquad
from numpy import exp, log as ln, e, isclose
from scipy import optimize

# make sure to do a pip install scipy

In [2]:
def integrateFunction(x):
    return x

In [3]:
# let us perform some double integrals

# y must be the first argument, and x the second
f = lambda y, x: x + y**2
dblquad(f, 0, 2, lambda x: x, lambda x: x**2)

(6.095238095238096, 2.4838925067764726e-13)

In [4]:
# optimization
print("Welcome back!")

Welcome back!


In [5]:
toMinimize = lambda x: x**2+ 3*x 

a = optimize.minimize(toMinimize, 0, method='bfgs')
b = optimize.root(toMinimize, [-100, 100], method="hybr")


In [6]:
from scipy import linalg
import numpy as np

matrix = np.array([
    [10, 4],
    [9, 7]
])

matrix

array([[10,  4],
       [ 9,  7]])

In [7]:
type(matrix)

numpy.ndarray

In [8]:
# common linear algebra techniques

print("Inverse: ", linalg.inv(matrix))
print("Determinant: ", linalg.det(matrix))

tt = np.array([1, 2])
linalg.solve(matrix, tt)

Inverse:  [[ 0.20588235 -0.11764706]
 [-0.26470588  0.29411765]]
Determinant:  34.0


array([-0.02941176,  0.32352941])

In [9]:
# how to calculate eigenvalues and eigenvectors
test_rating_data = np.array([
    [5, 8],
    [7, 9]
])

# print the EigenValues
eigenvalues, eigenvector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenvalues
print(first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [10]:
# print first eigenvectors
print(eigenvector[:, 0])

# print second eigenvector
print(eigenvector[:, 1])

[-0.81220939  0.58336601]
[-0.63447346 -0.77294465]


In [11]:
from scipy.stats import norm
# location is the mean and scale is the standard deviation for normal distribution

norm.rvs(loc=0, scale=1, size=10)

array([-1.8747855 ,  1.29850557, -1.10196112,  0.18487898, -1.39250586,
        0.04500254, -1.20623219, -0.55776048, -0.46267487, -1.36317676])

In [12]:
norm.cdf(5, loc=0, scale=2)

0.9937903346742238

In [13]:
norm.pdf(9, loc=0, scale=1)

1.0279773571668917e-18

In [14]:
o = {
    "name": "Emeka",
    "id": 22,
    "age": 20,
}
print(type(o))

<class 'dict'>
