In [2]:
import numpy as np

first_numpy_array = [1, 2, 3, 4]

[0.2        1.         0.75       0.66666667]


In [5]:
array_with_zeros = np.zeros((3, 3,))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# you can reshape an array to have another shape lol
np_arange = np.arange(12)

# reshape it to a 3 by 4 matrix
three_by_four = np_arange.reshape(12, 1)

#print(three_by_four)

In [20]:
np_linspace = np.linspace(1, 10, 1000)
#print(np_linspace)