In [1]:
import numpy as np

first_numpy_array = [1, 2, 3, 4]

In [2]:
array_with_zeros = np.zeros((3, 3,))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# you can reshape an array to have another shape lol
np_arange = np.arange(12)

# reshape it to a 3 by 4 matrix
three_by_four = np_arange.reshape(12, 1)

#print(three_by_four)

In [4]:
np_linspace = np.linspace(1, 10, 1000)
#print(np_linspace)

In [5]:
one_dim_array = np.array([1, 2, 3, 4, 50])
two_dim_array = np.array([
    [1, 2, 3, 4],
    [3, 5, 7 ,8]
])

print(two_dim_array[:, 0])

three_dim_array = np.array([
    [[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
    ],
    
    [[5, 6, 9],
    [8, 7, 2],
    [7, 99, 76]
    ],

])


print(two_dim_array.shape)
print(three_dim_array.shape)
print(three_dim_array.size)

[1 3]
(2, 4)
(2, 3, 3)
18


In [6]:
# let us say that we wanted to find out how many people worked 
# past twenty hours,and also over the age of 80

np_overTheAgeOfEighty = np.array([80, 33, 21, 90, 99, 88])
np_worked_overTime = np.array([40, 39, 0, 3, 22, 0])

# print(np.logical_and(np_worked_overTime >= 20, np_overTheAgeOfEighty >= 80))

In [7]:
# Understanding copying 

a1 = np.array([1, 2, 3])
a2 = a1

print(a1)
print(a2)

a1 = np.array([44, 44, 44])

[1 2 3]
[1 2 3]


In [8]:
# this means that we want 7 numbers between 4 and 13 (inclusive)
print(np.linspace(4, 13, 7))

[ 4.   5.5  7.   8.5 10.  11.5 13. ]


In [9]:
np_string_array = np.array(["emeka", "chidera"])
print(np_string_array.dtype)
# not sure what some of these data types mean but they will make sense eventually

<U7


In [10]:
# basic mathematics
np.add(12, 13)

np.sum(np.array([1, 2, 3, 4]))

# conditional sum
print(np.array([1, 2, 3, 4]) >= 2)

# numpy counts a True as 1, and a false as 0
np.sum(np.array([1, 2, 3, 4, 5]) >= 2)

[False  True  True  True]


4

In [11]:
two_d = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d[:, 1])

[2 5]


In [12]:
three_d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [4, 1 ,5],
        [6, 23, 66],
    ]
])
print(three_d[:, :, 1])
print(three_d.shape)

[[ 2  5]
 [ 1 23]]
(2, 2, 3)


In [13]:
# simple assignments do not create new arrays, they just reference the same array
parent_arr = np.array([1, 2, 3, 4])
child = parent_arr

print(child is parent_arr)

child[2] = 99
print(child, parent_arr)

True
[ 1  2 99  4] [ 1  2 99  4]


In [14]:
# shallow copies/views create new arrays, but they still reference the original array
parent_2 = np.array([1, 2, 3, 4])
child_2 = parent_2.view()

print("Before change: \n", parent_2, child_2)

child_2[0] = 111

print("After change: \n", parent_2, child_2)

# so then what is the difference between a shallow copy/view and simple assignments??

Before change: 
 [1 2 3 4] [1 2 3 4]
After change: 
 [111   2   3   4] [111   2   3   4]


In [15]:
# Deep copy enirely copies the original dataset as the copy is a separate object and does not refer to the original dataset
cop_of_parent_2 = parent_2.copy()
cop_of_parent_2 is parent_2

print("Before changing value in the deep copied array: \n", cop_of_parent_2, parent_2)

cop_of_parent_2[0] = 9099

print("After changing values in the copy of parent 2: \n", cop_of_parent_2, parent_2)

Before changing value in the deep copied array: 
 [111   2   3   4] [111   2   3   4]
After changing values in the copy of parent 2: 
 [9099    2    3    4] [111   2   3   4]


In [16]:
print("Hello world")

Hello world


In [17]:
# some common numpy mathematical examples
from numpy import pi

arr = np.array([1, 2, 3, 4])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


In [18]:
print(np.cos(0))
print(np.cos(pi))

1.0
-1.0


In [19]:
np_ones = np.ones((3, 3))
print(np_ones)

print("Bringing the ones array into a single row")
print(np.ravel(np_ones))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Bringing the ones array into a single row
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
three_by_four = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(three_by_four.shape) # (3, 4)
print(three_by_four.ndim)  # 2
print(three_by_four.size)  # # 12

print(f"Before reshaping: {three_by_four}.\n\n|After reshaping: {three_by_four.reshape(6, 2)}")


(3, 4)
2
12
Before reshaping: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]].

|After reshaping: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
# import webbrowser
# webbrowser.open("https://tesla.com")



In [24]:
# Numpy uses broadcasting to perform aritchmetic operations on arrays of different sizes

# example
a = np.array([1, 2, 3, 4])
b = np.array([0.2, 0.5, 6, 32])



[ 0.2  0.5  6.  32. ]


In [6]:
import numpy as np
tt = np.array([1, 2, True, "Nice", "Emeka", 33, 3, ])
print(tt.dtype)

<U21


In [7]:
print(np.transpose([1, 2, 3, 4]))

[1 2 3 4]


In [1]:
# from now, we start learning to use SciPy
print("Consistency is key")


Consistency is key


In [2]:
print("Software engineer at intel this coming fall semester??")

Software engineer at intel this coming fall semester??
